### PR TITLE
Additional integration tests

### PR DESCRIPTION
**Pull request by npollock14**
- non sample functions can now be run. Ex: `AddProductColumnTypes.cs` which should not be included in samples but should be tested
- added test with lots of possible data types to insert but not all
- configured the json serializer in async collector with a DateFormatString to make sure that date time objects are serialized properly

### CODE REVIEW

**Review by DaeunYim — COMMENTED** [review]
I'm assuming, there's duplicate files because this PR includes changes from the prior PR, right?

**Comment by npollock14** [comment]
> I'm assuming, there's duplicate files because this PR includes changes from the prior PR, right?

@DaeunYim Yeah, it was adding onto the previous pr. Just merged everything so should not have duplicates now.

**Comment by DaeunYim** [comment]
Had to mention this in the earlier PR, but in the integration test, rather than adding test.settings.json to .gitignore, add a template file as test.settings.json i.e., without host name and password and admin as postgres etc., so people can easily find out what kind of formatting they have to follow.

**Comment by npollock14** [comment]
> Had to mention this in the earlier PR, but in the integration test, rather than adding test.settings.json to .gitignore, add a template file as test.settings.json i.e., without host name and password and admin as postgres etc., so people can easily find out what kind of formatting they have to follow.

@DaeunYim 
Sounds good, added that in but was able to leave it included in gitignore. Is this fine or remove it from there as well?
Also added the remainder of the relevant output binding integration tests here.

**Comment by DaeunYim** [comment]
> > Had to mention this in the earlier PR, but in the integration test, rather than adding test.settings.json to .gitignore, add a template file as test.settings.json i.e., without host name and password and admin as postgres etc., so people can easily find out what kind of formatting they have to follow.
> 
> @DaeunYim Sounds good, added that in but was able to leave it included in gitignore. Is this fine or remove it from there as well? Also added the remainder of the relevant output binding integration tests here.

Sorry for going back and forth but what I mentioned was something like this so people don't have to come up with connection string and rather just fill in this template. 

{
    "host": "localhost",
    "port": 5432,
    "user": "postgres",
    "password": "",
    "dbname": "postgres"
}

**Review by DaeunYim — APPROVED** [review]
Nicely done!

**Pull request merged**
